//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceClaimRequest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benefit
    {
        public Benefit()
        {
            this.InsuranceLineItems = new HashSet<InsuranceLineItem>();
        }
    
        public int BenefitID { get; set; }
        public string BenefitCode { get; set; }
        public string BenefitName { get; set; }
        public Nullable<int> NormalBenefitPercentage { get; set; }
        public Nullable<int> EmergencyBenefitPercentage { get; set; }
    
        public virtual ICollection<InsuranceLineItem> InsuranceLineItems { get; set; }
    }
}
