//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceClaimRequest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;
    
    public partial class Insurance
    {
        public Insurance()
        {
            this.InsuranceLineItems = new HashSet<InsuranceLineItem>();
        }
        [Display(Name = "Insurer Id")]
        public string InsurerId { get; set; }
         [Display(Name = "Insurer Name")]
        public string InsurerName { get; set; }
        [Required]
        [Display(Name = "Date Of Birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
         private DateTime _DOB = DateTime.Now;

        public System.DateTime DOB
         {
             get
             {
                 return (_DOB == DateTime.Now) ? DateTime.Now : _DOB;
             }
             set
             {
                 _DOB = value;

             }
         }

         [Required]
         [Display(Name = "Date Of Birth")]
         [DataType(DataType.Date)]
         [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
         public System.DateTime? DateOfBirth {get; set; }

        [Required]
        [Display(Name = "Claim Received Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        private DateTime _claimRcvdDate = DateTime.Now;  // DateTime.MinValue;

        public System.DateTime ClaimRcvdDate
        {
            get
            {
                return (_claimRcvdDate == DateTime.Now) ? DateTime.Now: _claimRcvdDate;
            }
            set
            {
                _claimRcvdDate = value;
               
            }
        }
        [Required]
        [Display(Name = "Claim Received Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]

        public string ClaimReceivedDate
        {

            get
            {
               return DateTime.Now.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            set
            {
               

            }
        }

         [Display(Name = "Received Claim Amount")]
        public decimal ReceivedClaimAmount { get; set; }
         [Display(Name = "Total Approved Amount")]
        public decimal ApprovedTotalAmount { get; set; }
         [Display(Name = "Override Approved Amount")]
        public decimal ApprovedOverrideAmount { get; set; }
    
        public virtual ICollection<InsuranceLineItem> InsuranceLineItems { get; set; }
    }
}
